default:
  suites:
    default:
      autoload:
        '': %paths.base%/features/bootstrap
      contexts:
        - VarbaseContext:
            parameters:
              varbase_users:
                webmaster: { email: 'webmaster@vardot.com', password: 'dD.123123' }
        - SelectorsContext:
           parameters:
             files_path: "%paths.base%/selectors/"
             files:
               - "varbase/installation-selectors.yml"
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - behatch:browser:
            timeout: 1
        - behatch:debug:
            screenshotDir: "%paths.base%/screenshots/"
        - behatch:json:
            evaluationMode: javascript
        - behatch:rest
        - behatch:system:
            root: "/var/www/html/testing/docroot"
        - behatch:table
        - behatch:xml
      filters:
        tags: "@install"
      paths:
        features: %paths.base%/features
        bootstrap: %paths.base%/features/bootstrap
  formatters:
    pretty:
    html:
      output_path: "%paths.base%/reports/"
  extensions:
    Behat\MinkExtension:
      files_path: "%paths.base%/assets/"
      goutte: ~
      zombie: ~
      sahi: ~
      selenium2:
        wd_host: 127.0.0.1:4445/wd/hub
        capabilities:
          # browser: 'firefox'
          browser: 'chrome'
          # browser: 'phantomjs'
          nativeEvents: true
      base_url: http://localhost/testing/docroot
      # browser_name: 'firefox'
      browser_name: 'chrome'
      # browser_name: 'phantomjs'
      javascript_session: selenium2
    Drupal\DrupalExtension:
      blackbox: ~
    Sanpi\Behatch\Extension: ~
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: index
      print_args: false
      print_outp: false
      loop_break: false
